### ISSUE TITLE
Wallets with 100% ICX staked show 0 balance

### ISSUE THREAD

**Issue by radiofriendly** [icon-project/iconex_chrome_extension#29]
A few users have reported that they see a 0 balance in the ICONex Chrome extension when 100% of their coins have been staked.  Typically, when we attempt to stake our full balance a few ICX remain unstaked.  I'm not sure if these users were able to stake 100% of their coins, or if they staked their coins and moved the remaining few ICX out of the wallet after staking.

We have identified that sending an ICX coin to the wallet resolves the issue.  The user then sees their balance and is able to modify delegations or staked settings.

To Reproduce:  Create a wallet and stake all of the ICX you can.  Remove remaining ICX out of the wallet so 100% of the coins in the wallet have been staked and then try to access the wallet again.  You will notice a 0 balance.

To Resolve:  Send 1 or 2 ICX to this wallet.  The balance will now show again and the user will have access to the coins in the wallet.

**Comment by jorisvial** [comment]
Closing because it's too old. Feel free to re-open if you feel like a change is required.

**Comment by chisNaN** [comment]
Hello I reopen because I have "tried to stake icx on the chrome extension wallet
and as the vote section is empty i tried to unstake but its impossible the icx are locked in staked section
and cannot recover them!!!
Will it solve the issue if i try to reinstall an older working version of iconex chrome wallet?
Thanks for help because even its not a lot of money its really annoying
Hope someone can help
Thanks in advance
